### ISSUE TITLE
Syncing with Google Account

### ISSUE THREAD

**Issue by MarcinusX** [MSzalek-Mobile/weight_tracker#4]
User should be able to log in with Google Account so that he can access his data on any device.

**Comment by komputerboy** [comment]
why i cant log in with Google Account?

**Comment by komputerboy** [comment]
yes, thanks really good app.

**Comment by komputerboy** [comment]
Now, I got this error when opening Setting page

> I/flutter (14422): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (14422): The following assertion was thrown building StreamBuilder<_ViewModel>(dirty, state:
I/flutter (14422): _StreamBuilderBaseState<_ViewModel, AsyncSnapshot<_ViewModel>>#f65b4):
I/flutter (14422): 'package:flutter/src/painting/image_provider.dart': Failed assertion: line 451 pos 16: 'url !=
I/flutter (14422): null': is not true.
I/flutter (14422): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (14422): more information in this error message to help you determine and fix the underlying cause.
I/flutter (14422): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (14422):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (14422): When the exception was thrown, this was the stack:
I/flutter (14422): #2      new NetworkImage (package:flutter/src/painting/image_provider.dart:451:16)
I/flutter (14422): #3      ProfileView._loggedInView (package:weight_tracker/screens/profile_view.dart:30:21)
I/flutter (14422): #4      ProfileView.build.<anonymous closure> (package:weight_tracker/screens/profile_view.dart:22:15)
I/flutter (14422): #5      _StoreStreamListenerState.build.<anonymous closure> (package:flutter_redux/flutter_redux.dart)
I/flutter (14422): #6      StreamBuilder.build (package:flutter/src/widgets/async.dart:423:74)
I/flutter (14422): #7      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:125:48)
I/flutter (14422): #8      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
I/flutter (14422): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter (14422): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #12     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (14422): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #19     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (14422): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #34     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4965:32)
I/flutter (14422): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #45     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #46     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #47     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4047:11)
I/flutter (14422): #48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #49     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4965:32)
I/flutter (14422): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #55     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (14422): #56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #61     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #62     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #68     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (14422): #69     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #72     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter (14422): #73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #76     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #77     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #78     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #81     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter (14422): #82     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #85     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #86     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #87     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (14422): #88     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #92     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #93     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #94     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (14422): #95     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #96     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #99     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #100    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #101    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #107    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #108    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #111    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #112    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #113    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (14422): #114    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #115    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #118    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #119    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #120    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (14422): #121    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #122    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #123    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #125    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #126    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #127    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (14422): #128    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #129    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #130    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #132    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #133    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #134    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #135    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #136    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #138    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #139    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #140    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #141    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #142    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #143    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter (14422): #144    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #145    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #146    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #147    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #148    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #149    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #150    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #151    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #152    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter (14422): #153    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #154    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #155    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter (14422): #156    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #157    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #158    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter (14422): #159    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #160    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #161    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter (14422): #162    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #163    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #164    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #165    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #166    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #167    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (14422): #168    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #169    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #170    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #171    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #172    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #173    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #174    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #175    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #176    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #178    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #179    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #180    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (14422): #181    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #182    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #183    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #184    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter (14422): #185    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #186    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #187    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #188    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #189    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #190    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #191    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #192    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #193    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter (14422): #194    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #195    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #196    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #197    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #198    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #199    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (14422): #200    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #201    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #202    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #203    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #204    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #205    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #206    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #207    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #208    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #209    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter (14422): #210    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #211    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #212    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #213    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #214    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #215    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #216    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #217    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #218    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #219    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #220    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #221    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (14422): #222    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #223    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #224    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #225    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #226    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #227    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (14422): #228    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (14422): #229    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (14422): #230    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (14422): #231    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (14422): #232    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4643:32)
I/flutter (14422): #233    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4975:17)
I/flutter (14422): #234    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (14422): #235    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter (14422): #236    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (14422): #237    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #238    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #239    StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (14422): #240    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (14422): #241    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #242    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #243    ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (14422): #244    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (14422): #245    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (14422): #246    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (14422): #247    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #248    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #249    StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (14422): #250    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (14422): #251    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (14422): #252    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (14422): #253    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (14422): #254    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (14422): #255    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (14422): #256    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14422): #257    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter (14422): #258    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
I/flutter (14422): #259    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (14422): #260    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (14422): #261    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (14422): #262    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (14422): #263    _invoke (dart:ui/hooks.dart:154:13)
I/flutter (14422): #264    _drawFrame (dart:ui/hooks.dart:143:3)

**Comment by komputerboy** [comment]
Now i cant sync with my google account again...

**Comment by MarcinusX** [comment]
Hmm... the error you listed should be fixed with a simple null check, but can you provide some more details on the latter issue?

**Comment by komputerboy** [comment]
Try to download it again, then rebuild/install again with new fresh file, not changing anything. and then try to sign in with google. 
But still show this error..

> E/flutter (13244): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (13244): PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 12500: , null)
E/flutter (13244): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter (13244): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
E/flutter (13244): <asynchronous suspension>
E/flutter (13244): #2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:217:58)
E/flutter (13244): <asynchronous suspension>
E/flutter (13244): #3      GoogleSignIn._addMethodCall.<anonymous closure> (package:google_sign_in/google_sign_in.dart:269:28)
E/flutter (13244): #4      _RootZone.run (dart:async/zone.dart:1374:54)
E/flutter (13244): #5      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:153:18)
E/flutter (13244): #6      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:612:39)
E/flutter (13244): #7      Future._propagateToListeners (dart:async/future_impl.dart:668:37)
E/flutter (13244): #8      Future._addListener.<anonymous closure> (dart:async/future_impl.dart:351:9)
E/flutter (13244): #9      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (13244): #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by MarcinusX** [comment]
Do you have FirebaseAuth and GoogleSignIn enabled in Firebase project?

**Comment by komputerboy** [comment]
I'm not changing anything from your project, so it still use your Firebase project .json. And it show error like above.

I also try to use my own Firebase json. with auth and googlesignin, anonymous enabled. 
If i use anonymous it works, but when i use googlesignin it fail.
